
services:
  fastapi_backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./vectorstore:/app/vectorstore

  streamlit_frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://fastapi_backend:8000
    depends_on:
      - fastapi_backend